### ISSUE TITLE
Add instructions to compile or publish an AUR pkg

### ISSUE THREAD

**Issue by Twig6943** [DarkVanityOfLight/ZSnoW#2]
title.

**Comment by DarkVanityOfLight** [comment]
@jorrmungandrr It looks like you are missing the layer shell protocol. It is part of the [wlr-protocols](https://gitlab.freedesktop.org/wlroots/wlr-protocols/). On arch they are in the `wlr-protocols` package(`sudo pacman -Sy wlr-protocols`). 
I'm happy to add some docs about building/compiling.

**Comment by Twig6943** [comment]
@DarkVanityOfLight now that this is done what aboit an appimage?

**Comment by DarkVanityOfLight** [comment]
At the current time I won't provide an appimg. The code still has some flaws and I don't want to republish/create a release every time I make some changes to the code.

**Comment by Twig6943** [comment]
ANY eta for the first stable release? (A build thats worth making an appimage of)

**Comment by DarkVanityOfLight** [comment]
No clue it always depends on how much time I have, and how much coding I want to do :3
